services:
  backend-server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
  frontend-client:
    build: ./client
    ports:
      - "8000:8000"
    networks:
      - backend-network
  mongo:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test:
      - CMD
      - mongosh
      - --eval
      - "db.adminCommand('ping')"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - PUID=1000
      - PGID=1000

volumes:
  mongodb:
