services:
  backend-server:
    build: ./server
    networks:
      - backend-network
      - db-network
    depends_on:
      mongo:
        condition: service_healthy
  frontend-client:
    build: ./client
    network_mode: "host"
    networks:
      - backend-network
  mongo:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    networks:
      - db-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb:

networks:
  backend-network:
  db-network:
